# Generated by Django 4.2.7 on 2023-11-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animation',
            old_name='file',
            new_name='file30',
        ),
        migrations.AddField(
            model_name='animation',
            name='file60',
            field=models.FileField(default='exit', upload_to='animations/file/%y/%m/%d/'),
            preserve_default=False,
        ),
    ]
