# Generated by Django 4.2.7 on 2023-11-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_company_requesttype_usertype_alter_animation_file30_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animation',
            name='body_category',
        ),
        migrations.RemoveField(
            model_name='animation',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='animation',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='animation',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='request',
            name='type',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
        migrations.DeleteModel(
            name='Animation',
        ),
        migrations.DeleteModel(
            name='BodyCategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='RequestType',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
