# Generated by Django 4.2.7 on 2023-11-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
